### ISSUE TITLE
NodeApiError: Cannot read properties of undefined (reading 'split') at Object.tiktokApiRequest 

### ISSUE THREAD

**Issue by erikdemarco** [igabm/n8n-nodes-tiktok#3]
I got error when testing photo upload:

`NodeApiError: Cannot read properties of undefined (reading 'split') at Object.tiktokApiRequest (/home/node/.n8n/nodes/node_modules/@igabm/n8n-nodes-tiktok/nodes/TikTok/V2/GenericFunctions.ts:48:9) at Object.execute (/home/node/.n8n/nodes/node_modules/@igabm/n8n-nodes-tiktok/nodes/TikTok/V2/TikTokV2.node.ts:115:22) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:711:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1141:20`

**Comment by rumyantsevaT** [comment]
I have the same problem

**Comment by Morteza-Rastgoo** [comment]
Any updates on this?

**Comment by igabm** [comment]
Has been fixed, feel free to update and test, thanks for your feedback.
